# Site settings
title: Bruno's Journal
email: brunofr@olympum.com
description: "Bruno Fernandez-Ruiz's Journal"
url: "http://www.olympum.com"
production_url : http://www.olympum.com
permalink: /:categories/:title/
twitter_username: olympum
github_username:  olympum

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
theme: minima

gems:
  - jekyll-paginate
  - jekyll-feed

exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - .rvmrc
  - .rbenv-version
  - changelog.md

# Collections:
collections:
  essays:
    output: true
    permalink: /:collection/:path/
