# Site settings
title: Bruno's Journal
email: brunofr@olympum.com
description: "Bruno Fernandez-Ruiz's Journal"
url: "http://www.olympum.com"
production_url : http://www.olympum.com
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
permalink: /:categories/:title
twitter_username: olympum
github_username:  olympum

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
show_drafts: true

# Collections:
collections:
  essays:
    output: true
    permalink: /essays/:path/

gems:
  - jekyll-paginate
