version: '2'

services:
    jekyll:
        image: jekyll/builder:3.3.0
#        environment:
#            - JEKYLL_ENV=production
        command: jekyll serve --incremental
        volumes:
            - .:/srv/jekyll
        ports:
            - 4000:4000
